name: Build PS2EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install PS2EXE
      shell: powershell
      run: |
        Install-Module -Name ps2exe -Force -Scope CurrentUser
    - name: Create bin directory
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path bin
    - name: Compile script
      shell: powershell
      run: |
        Invoke-ps2exe -InputFile run.ps1 -OutputFile "bin/run.exe"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-executable
        path: bin/